# Generated by Django 2.2.12 on 2020-04-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200422_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_date',
        ),
    ]
